apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
spec:
  ports:
    - port: 80
      targetPort: 5672
  selector:
    app: rabbitmq

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8.3
          ports:
            - containerPort: 5672
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"     
            limits:
              memory: "1Gi"
              cpu: "1"     
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: guest
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
