apiVersion: v1
kind: Service
metadata:
  name: receiver-service
spec:
  ports:
    - port: 80
      targetPort: 8091
  selector:
    app: receiver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
        - name: receiver
          image: reverendray/receiver-service:0.0.1
          ports:
            - containerPort: 8091
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq-svc
