apiVersion: v1
kind: Service
metadata:
  name: sender-service
spec:
  ports:
    - port: 80
      targetPort: 8090
  selector:
    app: sender
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
        - name: sender
          image: reverendray/sender-service:0.0.1
          ports:
            - containerPort: 8090
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq-svc
