# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Nurol CI/CD Deploy Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
        
    - name: "Install Kubectl"
      uses: alexellis/arkade-get@23907b6f8cec5667c9a4ef724adea073d677e221
      with:
        kubectl: latest
        
    - name: Authenticate with EKS cluster
      run: aws eks --region eu-north-1 update-kubeconfig --name nurol-cluster

    - name: Deploy to Amazon EKS
      run: kubectl apply -f k8s/
