# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Nurol CI/CD Build&Deploy Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up AWS EKS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-north-1
          aws-cluster-name: <EKS_CLUSTER_NAME>
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to Amazon EKS
        run: kubectl apply -f k8s/ --validate=false
